// ── Seed data ────────────────────────────────────────────────────────────────
// Used to initialise Firestore on first run

const P_SEED = {
  saffron:"#E8821A",gold:"#C9960C",purple:"#6B3FA0",muted:"#9B7355",
  deepBrown:"#5C2A0A",success:"#1A7A40"
};

const RTYPE_SEED=[
  {id:"sambar",        en:"Sambar",          ta:"சாம்பார்",       color:P_SEED.saffron},
  {id:"kuzhambu",      en:"Kuzhambu",        ta:"குழம்பு",         color:"#B45309"},
  {id:"rasam",         en:"Rasam",           ta:"ரசம்",             color:"#92400E"},
  {id:"kootu",         en:"Kootu",           ta:"கூட்டு",           color:"#065F46"},
  {id:"vellai_poriyal",en:"Vellai Poriyal",  ta:"வெள்ளை பொரியல்", color:"#2E7D32"},
  {id:"kara_poriyal",  en:"Kara Poriyal",    ta:"கார பொரியல்",      color:"#C0392B"},
  {id:"pachadi",       en:"Pachadi",         ta:"பச்சடி",           color:"#1A6B8A"},
  {id:"mandi",         en:"Mandi / Kolambu", ta:"மண்டி / கொழம்பு", color:"#6B3FA0"},
  {id:"payasam",       en:"Payasam",         ta:"பாயசம்",           color:P_SEED.gold},
  {id:"piece_sweet",   en:"Piece Sweet",     ta:"பீஸ் இனிப்பு",    color:"#DB2777"},
  {id:"bulk_sweet",    en:"Bulk Sweet",      ta:"மொத்த இனிப்பு",   color:"#BE185D"},
  {id:"rice",          en:"Rice / Sadam",    ta:"சாதம்",            color:P_SEED.deepBrown},
  {id:"tiffin",        en:"Tiffin",          ta:"டிஃபின்",          color:"#0EA5E9"},
  {id:"chutney",       en:"Chutney",         ta:"சட்னி",            color:"#2E7D32"},
  {id:"salad",         en:"Salad / Raita",   ta:"சாலட் / பச்சடி",  color:"#0D9488"},
  {id:"gravy",         en:"Gravy / Curry",   ta:"கிரேவி",           color:"#7C3AED"},
  {id:"sub",           en:"Sub-Recipe/Base", ta:"துணை சமையல்",      color:P_SEED.purple},
  {id:"other",         en:"Other",           ta:"மற்றவை",           color:P_SEED.muted},
];

// ── Full ingredient master (703 items from KAL Karaikudi) ─────────────────────
// normCost is 0 — fill in actual prices after import
const ING0=[
  {id:1000,name:"Water for Dal",nameTamil:"பருப்புக்கான தண்ணீர்",category:"grocery",unit:"L",normCost:0},
  {id:1001,name:"A - Kuzhambu Yaedai",nameTamil:"A - குழம்பு எடை",category:"grocery",unit:"kg",normCost:0},
  {id:1002,name:"A Atiya Maavu weight",nameTamil:"A அடித்த மாவு எடை",category:"grocery",unit:"g",normCost:0},
  {id:1003,name:"A Boondi weight",nameTamil:"A பூந்தி எடை",category:"grocery",unit:"kg",normCost:0},
  {id:1004,name:"A Karaitha Mavu Weight",nameTamil:"A கரைத்த மாவு எடை",category:"grocery",unit:"kg",normCost:0},
  {id:1005,name:"AC Paneer",nameTamil:"AC பனீர்",category:"grocery",unit:"kg",normCost:0},
  {id:1006,name:"AC Roasted Chick Peas",nameTamil:"AC வறுத்த கொண்டைக்கடலை",category:"grocery",unit:"kg",normCost:0},
  {id:1007,name:"Aavin Milk Powder",nameTamil:"ஆவின் பால் பொடி",category:"grocery",unit:"L",normCost:0},
  {id:1008,name:"Achhu Vellam",nameTamil:"அச்சு வெல்லம்",category:"grocery",unit:"kg",normCost:0},
  {id:1009,name:"Achi Masala Gobi 65",nameTamil:"ஆச்சி மசாலா கோபி 65",category:"grocery",unit:"g",normCost:0},
  {id:1010,name:"After grinding batter wt",nameTamil:"அரைத்த பிறகு மாவு எடை",category:"grocery",unit:"kg",normCost:0},
  {id:1011,name:"Ajinomotto",nameTamil:"அஜினோமோட்டோ",category:"grocery",unit:"kg",normCost:0},
  {id:1012,name:"Almond",nameTamil:"பாதாம்",category:"grocery",unit:"g",normCost:0},
  {id:1013,name:"Amul Butter (Saltless)",nameTamil:"அமுல் உப்பு இல்லாத வெண்ணெய்",category:"grocery",unit:"g",normCost:0},
  {id:1014,name:"Amul Butter Yellow",nameTamil:"அமுல் மஞ்சள் வெண்ணெய்",category:"grocery",unit:"g",normCost:0},
  {id:1015,name:"Amul Cheese",nameTamil:"அமுல் சீஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1016,name:"Amul Milk Maid",nameTamil:"அமுல் மில்க்மெய்ட்",category:"grocery",unit:"L",normCost:0},
  {id:1017,name:"Anil Thinai Vermicilli",nameTamil:"அனில் திணை சேமியா",category:"grocery",unit:"kg",normCost:0},
  {id:1018,name:"Anil Varagu Vermicelli",nameTamil:"அனில் வரகு சேமியா",category:"grocery",unit:"kg",normCost:0},
  {id:1019,name:"Anise",nameTamil:"சோம்பு",category:"grocery",unit:"g",normCost:0},
  {id:1020,name:"Annasi Poo",nameTamil:"அன்னாசிப் பூ",category:"grocery",unit:"kg",normCost:0},
  {id:1021,name:"Appa Plate",nameTamil:"அப்பா தட்டு",category:"grocery",unit:"nos",normCost:0},
  {id:1022,name:"Appalam Big",nameTamil:"பெரிய அப்பளம்",category:"grocery",unit:"kg",normCost:0},
  {id:1023,name:"Appalam Small",nameTamil:"சிறிய அப்பளம்",category:"grocery",unit:"kg",normCost:0},
  {id:1024,name:"Apple Cider Vinegar",nameTamil:"ஆப்பிள் சைடர் வினிகர்",category:"grocery",unit:"L",normCost:0},
  {id:1025,name:"Asfoetida",nameTamil:"பெருங்காயம்",category:"grocery",unit:"kg",normCost:0},
  {id:1026,name:"Aval",nameTamil:"அவல்",category:"grocery",unit:"kg",normCost:0},
  {id:1027,name:"Badham Halwa Pottadhu",nameTamil:"பாதாம் அல்வா போட்டது",category:"grocery",unit:"kg",normCost:0},
  {id:1028,name:"Badham Pisin",nameTamil:"பாதாம் பிசின்",category:"grocery",unit:"kg",normCost:0},
  {id:1029,name:"Bangalore Puli",nameTamil:"பெங்களூர் புளி",category:"grocery",unit:"kg",normCost:0},
  {id:1030,name:"Barley",nameTamil:"பார்லி",category:"grocery",unit:"kg",normCost:0},
  {id:1031,name:"Basic Gravy (Red)",nameTamil:"அடிப்படை கிரேவி (சிவப்பு)",category:"grocery",unit:"kg",normCost:0},
  {id:1032,name:"Basic Gravy (Yellow)",nameTamil:"அடிப்படை கிரேவி (மஞ்சள்)",category:"grocery",unit:"kg",normCost:0},
  {id:1033,name:"Basil",nameTamil:"பேசில்",category:"grocery",unit:"kg",normCost:0},
  {id:1034,name:"Basundhi",nameTamil:"பாசுந்தி",category:"grocery",unit:"kg",normCost:0},
  {id:1035,name:"Bay Leaf",nameTamil:"பிரியாணி இலை",category:"grocery",unit:"g",normCost:0},
  {id:1036,name:"Big Rava",nameTamil:"பெரிய ரவை",category:"grocery",unit:"g",normCost:0},
  {id:1037,name:"Black Cardamom",nameTamil:"கருப்பு ஏலக்காய்",category:"grocery",unit:"g",normCost:0},
  {id:1038,name:"Black Salt",nameTamil:"கருப்பு உப்பு",category:"grocery",unit:"g",normCost:0},
  {id:1039,name:"Black Sesame Seed",nameTamil:"கருப்பு எள்",category:"grocery",unit:"g",normCost:0},
  {id:1040,name:"Black Stone Flower",nameTamil:"கல் பாசி",category:"grocery",unit:"kg",normCost:0},
  {id:1041,name:"Bread",nameTamil:"பிரெட்",category:"grocery",unit:"kg",normCost:0},
  {id:1042,name:"Brown Sugar",nameTamil:"பிரவுன் சர்க்கரை",category:"grocery",unit:"g",normCost:0},
  {id:1043,name:"Cardamom",nameTamil:"ஏலக்காய்",category:"grocery",unit:"g",normCost:0},
  {id:1044,name:"Carrot Halwa (Prepared)",nameTamil:"கேரட் அல்வா (தயார்)",category:"grocery",unit:"kg",normCost:0},
  {id:1045,name:"Carrot Payasam",nameTamil:"கேரட் பாயாசம்",category:"grocery",unit:"kg",normCost:0},
  {id:1046,name:"Carrot Thirukiyathu",nameTamil:"துருவிய கேரட்",category:"grocery",unit:"kg",normCost:0},
  {id:1047,name:"Cashew",nameTamil:"முந்திரி",category:"grocery",unit:"g",normCost:0},
  {id:1048,name:"Cashew First Quality",nameTamil:"முதல் தர முந்திரி",category:"grocery",unit:"g",normCost:0},
  {id:1049,name:"Celary Salt",nameTamil:"செலரி உப்பு",category:"grocery",unit:"g",normCost:0},
  {id:1050,name:"Channa masala",nameTamil:"சன்னா மசாலா",category:"grocery",unit:"g",normCost:0},
  {id:1051,name:"Cheesy Corn Nuggers",nameTamil:"சீசி கார்ன் நகெட்ஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1052,name:"Cherry",nameTamil:"செர்ரி",category:"grocery",unit:"kg",normCost:0},
  {id:1053,name:"Chilli Flakes",nameTamil:"மிளகாய் ஃப்ளேக்ஸ்",category:"grocery",unit:"g",normCost:0},
  {id:1054,name:"Chilly - North Indian chilli",nameTamil:"மிளகாய் - வட இந்திய மிளகாய்",category:"grocery",unit:"g",normCost:0},
  {id:1055,name:"Chilly - Red Chilli",nameTamil:"மிளகாய் - சிவப்பு மிளகாய்",category:"grocery",unit:"g",normCost:0},
  {id:1056,name:"Chilly - Red Chilli( New)",nameTamil:"மிளகாய் - சிவப்பு மிளகாய் (புதியது)",category:"grocery",unit:"g",normCost:0},
  {id:1057,name:"Chilly - Samba Chilli",nameTamil:"மிளகாய் - சம்பா மிளகாய்",category:"grocery",unit:"g",normCost:0},
  {id:1058,name:"Ching Masala",nameTamil:"சிங் மசாலா",category:"grocery",unit:"g",normCost:0},
  {id:1059,name:"Chinna Cholam Maavu",nameTamil:"சின்ன சோள மாவு",category:"grocery",unit:"g",normCost:0},
  {id:1060,name:"Chola Ravai",nameTamil:"சோள ரவை",category:"grocery",unit:"g",normCost:0},
  {id:1061,name:"Cinnamon",nameTamil:"பட்டை",category:"grocery",unit:"kg",normCost:0},
  {id:1062,name:"Cinnamon(pattai)",nameTamil:"பட்டை",category:"grocery",unit:"kg",normCost:0},
  {id:1063,name:"Clove",nameTamil:"கிராம்பு",category:"grocery",unit:"g",normCost:0},
  {id:1064,name:"Coconut - Second milk",nameTamil:"தேங்காய் - இரண்டாம் பால்",category:"grocery",unit:"L",normCost:0},
  {id:1065,name:"Coconut - the first milk",nameTamil:"தேங்காய் - முதல் பால்",category:"grocery",unit:"L",normCost:0},
  {id:1066,name:"Coconut - the third milk",nameTamil:"தேங்காய் - மூன்றாம் பால்",category:"grocery",unit:"L",normCost:0},
  {id:1067,name:"Coconut Cream",nameTamil:"தேங்காய் கிரீம்",category:"grocery",unit:"L",normCost:0},
  {id:1068,name:"Coconut milk",nameTamil:"தேங்காய் பால்",category:"grocery",unit:"L",normCost:0},
  {id:1069,name:"Coffe Thulukku Thaneer",nameTamil:"காபி துளுக்கு தண்ணீர்",category:"grocery",unit:"kg",normCost:0},
  {id:1070,name:"Coriander",nameTamil:"கொத்தமல்லி",category:"grocery",unit:"kg",normCost:0},
  {id:1071,name:"Corn Flakes",nameTamil:"கார்ன் ஃப்ளேக்ஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1072,name:"Corn Meal",nameTamil:"சோள மாவு",category:"grocery",unit:"kg",normCost:0},
  {id:1073,name:"Corn Rava",nameTamil:"சோள ரவை",category:"grocery",unit:"g",normCost:0},
  {id:1074,name:"Cothas Coffee Powder",nameTamil:"கோதாஸ் காபி பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1075,name:"Crystal Salt",nameTamil:"கல் உப்பு",category:"grocery",unit:"g",normCost:0},
  {id:1076,name:"Crystal Salt for Veg",nameTamil:"காய்கறிக்கான கல் உப்பு",category:"grocery",unit:"g",normCost:0},
  {id:1077,name:"Cucumber Seed",nameTamil:"வெள்ளரி விதை",category:"grocery",unit:"g",normCost:0},
  {id:1078,name:"Cumin Seeds",nameTamil:"சீரகம்",category:"grocery",unit:"g",normCost:0},
  {id:1079,name:"Cumin for Seasoning",nameTamil:"தாளிப்புக்கான சீரகம்",category:"grocery",unit:"kg",normCost:0},
  {id:1080,name:"Cup- Paal Paniyara Cup",nameTamil:"கப் - பால் பணியார கப்",category:"grocery",unit:"nos",normCost:0},
  {id:1081,name:"Cup-Coffee,Tea,Payasam Cup",nameTamil:"கப் - காபி, தேநீர், பாயாச கப்",category:"grocery",unit:"nos",normCost:0},
  {id:1082,name:"Cup-Mini Idly Cup&Spoon",nameTamil:"கப் - மினி இட்லி கப் மற்றும் ஸ்பூன்",category:"grocery",unit:"nos",normCost:0},
  {id:1083,name:"Curry Leaf Podi",nameTamil:"கருவேப்பிலைப் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1084,name:"DP - American Seasoning Powder",nameTamil:"DP - அமெரிக்கன் சீசனிங் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1085,name:"DP - Anardhana Powder",nameTamil:"DP - மாதுளை விதை பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1086,name:"DP - Andhra Sambar Karam",nameTamil:"DP - ஆந்திரா சாம்பார் காரம்",category:"grocery",unit:"kg",normCost:0},
  {id:1087,name:"DP - Anise powder",nameTamil:"DP - சோம்பு பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1088,name:"DP - Baby Corn,Mushroom Fry Flour",nameTamil:"DP - பேபி கார்ன், காளான் வறுவல் மாவு",category:"grocery",unit:"g",normCost:0},
  {id:1089,name:"DP - Baja Masala",nameTamil:"DP - பஜா மசாலா",category:"grocery",unit:"g",normCost:0},
  {id:1090,name:"DP - Baking Powder",nameTamil:"DP - பேக்கிங் பவுடர்",category:"grocery",unit:"g",normCost:0},
  {id:1091,name:"DP - Baking soda",nameTamil:"DP - பேக்கிங் சோடா",category:"grocery",unit:"kg",normCost:0},
  {id:1092,name:"DP - Basen",nameTamil:"DP - கடலை மாவு",category:"grocery",unit:"kg",normCost:0},
  {id:1093,name:"DP - Bay Leaves Flour",nameTamil:"DP - பிரியாணி இலை பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1094,name:"DP - Bengal Gram Flour",nameTamil:"DP - கடலை மாவு",category:"grocery",unit:"g",normCost:0},
  {id:1095,name:"DP - BourneVita",nameTamil:"DP - போர்ன்விட்டா",category:"grocery",unit:"kg",normCost:0},
  {id:1096,name:"DP - Bush Red Color",nameTamil:"DP - புஷ் சிவப்பு கலர்",category:"grocery",unit:"kg",normCost:0},
  {id:1097,name:"DP - Cardamom Powder",nameTamil:"DP - ஏலக்காய் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1098,name:"DP - Chat Masala",nameTamil:"DP - சாட் மசாலா",category:"grocery",unit:"g",normCost:0},
  {id:1099,name:"DP - Chilli Powder",nameTamil:"DP - மிளகாய் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1100,name:"DP - Chilli Powder (CATCH)",nameTamil:"DP - மிளகாய் பொடி (CATCH)",category:"grocery",unit:"g",normCost:0},
  {id:1101,name:"DP - Chilli Powder (NEW)",nameTamil:"DP - மிளகாய் பொடி (NEW)",category:"grocery",unit:"g",normCost:0},
  {id:1102,name:"DP - Cocoa Powder",nameTamil:"DP - கோக்கோ பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1103,name:"DP - Coriander powder",nameTamil:"DP - தனியா பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1104,name:"DP - Corn Flour to mix up",nameTamil:"DP - கலப்பதற்கான கார்ன் ஃப்ளோர்",category:"grocery",unit:"g",normCost:0},
  {id:1105,name:"DP - Corn flour",nameTamil:"DP - கார்ன் ஃப்ளோர்",category:"grocery",unit:"g",normCost:0},
  {id:1106,name:"DP - Custard Powder",nameTamil:"DP - கஸ்டர்ட் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1107,name:"DP - Drinking Chocolate",nameTamil:"DP - குடிக்கும் சாக்லேட்",category:"grocery",unit:"kg",normCost:0},
  {id:1108,name:"DP - Fried White Sesame",nameTamil:"DP - வறுத்த வெள்ளை எள்",category:"grocery",unit:"g",normCost:0},
  {id:1109,name:"DP - Garam Masala",nameTamil:"DP - கரம் மசாலா",category:"grocery",unit:"g",normCost:0},
  {id:1110,name:"DP - Ginger powder",nameTamil:"DP - இஞ்சி பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1111,name:"DP - Gobi Fry Ma",nameTamil:"DP - கோபி வறுவல் மாவு",category:"grocery",unit:"kg",normCost:0},
  {id:1112,name:"DP - Idiyappa Ma",nameTamil:"DP - இடியாப்ப மாவு",category:"grocery",unit:"kg",normCost:0},
  {id:1113,name:"DP - Idli Powder",nameTamil:"DP - இட்லி பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1114,name:"DP - Idly Podi",nameTamil:"DP - இட்லி பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1115,name:"DP - Jadhipathri Powder",nameTamil:"DP - ஜாதிப்பத்திரி பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1116,name:"DP - Jeera Powder",nameTamil:"DP - சீரகப் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1117,name:"DP - Kashmiri Chilli Powder",nameTamil:"DP - காஷ்மீரி மிளகாய் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1118,name:"DP - Kesari powder",nameTamil:"DP - கேசரி பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1119,name:"DP - Kummaya flour",nameTamil:"DP - கும்மாய மாவு",category:"grocery",unit:"g",normCost:0},
  {id:1120,name:"DP - Kuruvai Rice Flour",nameTamil:"DP - குறுவை அரிசி மாவு",category:"grocery",unit:"g",normCost:0},
  {id:1121,name:"DP - Madras Curry Powder",nameTamil:"DP - மெட்ராஸ் கரி பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1122,name:"DP - Maida Flour for Breading",nameTamil:"DP - பிரெட்டிங் செய்ய மைதா மாவு",category:"grocery",unit:"g",normCost:0},
  {id:1123,name:"DP - Maida Ma",nameTamil:"DP - மைதா மாவு",category:"grocery",unit:"kg",normCost:0},
  {id:1124,name:"DP - Manchurian Flour",nameTamil:"DP - மஞ்சூரியன் மாவு",category:"grocery",unit:"g",normCost:0},
  {id:1125,name:"DP - Mass Almond Mix",nameTamil:"DP - மாஸ் பாதாம் மிக்ஸ்",category:"grocery",unit:"g",normCost:0},
  {id:1126,name:"DP - Nutmeg Powder",nameTamil:"DP - ஜாதிக்காய் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1127,name:"DP - Nutrient Ma",nameTamil:"DP - நியூட்ரியண்ட் மாவு",category:"grocery",unit:"kg",normCost:0},
  {id:1128,name:"DP - Onion Powder",nameTamil:"DP - வெங்காயப் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1129,name:"DP - Paiyara Rice Flour",nameTamil:"DP - பயற் அரிசி மாவு",category:"grocery",unit:"g",normCost:0},
  {id:1130,name:"DP - Pepper Powder",nameTamil:"DP - மிளகு பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1131,name:"DP - Pepper,Jeera Powder",nameTamil:"DP - மிளகு, சீரகப் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1132,name:"DP - Pomegranate powder",nameTamil:"DP - மாதுளை பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1133,name:"DP - Poriyal Powder",nameTamil:"DP - பொரியல் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1134,name:"DP - Potato Starch",nameTamil:"DP - உருளைக்கிழங்கு ஸ்டார்ச்",category:"grocery",unit:"g",normCost:0},
  {id:1135,name:"DP - Puli Curry Powder",nameTamil:"DP - புளிக் குழம்பு பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1136,name:"DP - Rasa Powder",nameTamil:"DP - ரசப் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1137,name:"DP - Raw Rice flour",nameTamil:"DP - பச்சரிசி மாவு",category:"grocery",unit:"g",normCost:0},
  {id:1138,name:"DP - Rice Upma flour",nameTamil:"DP - அரிசி உப்புமா மாவு",category:"grocery",unit:"g",normCost:0},
  {id:1139,name:"DP - Roasted Cumin Powder",nameTamil:"DP - வறுத்த சீரகப் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1140,name:"DP - Roasted pepper powder",nameTamil:"DP - வறுத்த மிளகு பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1141,name:"DP - Rusk Powder",nameTamil:"DP - ரஸ்க் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1142,name:"DP - Sambar Podi",nameTamil:"DP - சாம்பார் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1143,name:"DP - Sambar Topping Podi",nameTamil:"DP - சாம்பார் டாப்பிங் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1144,name:"DP - Sambar Topping Powder",nameTamil:"DP - சாம்பார் டாப்பிங் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1145,name:"DP - Soy flour",nameTamil:"DP - சோயா மாவு",category:"grocery",unit:"g",normCost:0},
  {id:1146,name:"DP - Sugar Powder",nameTamil:"DP - சர்க்கரை பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1147,name:"DP - Suku Malli",nameTamil:"DP - சுக்கு மல்லி",category:"grocery",unit:"kg",normCost:0},
  {id:1148,name:"DP - Tea",nameTamil:"DP - தேநீர்",category:"grocery",unit:"kg",normCost:0},
  {id:1149,name:"DP - Turmeric Powder( For Veg)",nameTamil:"DP - மஞ்சள் பொடி (காய்கறிக்காக)",category:"grocery",unit:"g",normCost:0},
  {id:1150,name:"DP - Turmeric powder",nameTamil:"DP - மஞ்சள் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1151,name:"DP - Urad, Pasiparuppu",nameTamil:"DP - உளுந்து, பாசிப்பருப்பு",category:"grocery",unit:"kg",normCost:0},
  {id:1152,name:"DP - Vangibath Powder",nameTamil:"DP - வாங்கிபாத் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1153,name:"DP - Vendhaya Powder",nameTamil:"DP - வெந்தயப் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1154,name:"DP - Wheat flour",nameTamil:"DP - கோதுமை மாவு",category:"grocery",unit:"g",normCost:0},
  {id:1155,name:"DP - Wheat flour for Dusting",nameTamil:"DP - தூவுவதற்கான கோதுமை மாவு",category:"grocery",unit:"g",normCost:0},
  {id:1156,name:"DP - maida flour for dipping",nameTamil:"DP - முக்குவதற்கான மைதா மாவு",category:"grocery",unit:"g",normCost:0},
  {id:1157,name:"DP - sambar powder",nameTamil:"DP - சாம்பார் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1158,name:"DP - whole garam masala",nameTamil:"DP - முழு கரம் மசாலா",category:"grocery",unit:"g",normCost:0},
  {id:1159,name:"DP -Panko Bread Crumbs",nameTamil:"DP - பாங்கோ பிரெட் தூள்",category:"grocery",unit:"kg",normCost:0},
  {id:1160,name:"DP- Dhania Powder",nameTamil:"DP- தனியா பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1161,name:"DP-Amchur Powder",nameTamil:"DP- ஆம்சூர் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1162,name:"DP-Black Pepper Powder Coarse",nameTamil:"DP - கருப்பு மிளகு பொடி (கொரகொரப்பானது)",category:"grocery",unit:"g",normCost:0},
  {id:1163,name:"DP-Coffee Powder",nameTamil:"DP- காபி பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1164,name:"DP-Ginger Powder",nameTamil:"DP- இஞ்சி பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1165,name:"Dakshin - Sambar Powder 2",nameTamil:"தக்ஷின் - சாம்பார் பொடி 2",category:"grocery",unit:"g",normCost:0},
  {id:1166,name:"Dakshin - Sambar Powder I",nameTamil:"தக்ஷின் - சாம்பார் பொடி I",category:"grocery",unit:"g",normCost:0},
  {id:1167,name:"Dakshin KP - Poriyal Powder",nameTamil:"தக்ஷின் KP - பொரியல் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1168,name:"Dates",nameTamil:"பேரீச்சம் பழம்",category:"grocery",unit:"g",normCost:0},
  {id:1169,name:"Dhall - Bengal Gram",nameTamil:"பருப்பு - கடலைப் பருப்பு",category:"grocery",unit:"kg",normCost:0},
  {id:1170,name:"Dhall - Black Channa",nameTamil:"பருப்பு - கருப்பு கொண்டைக்கடலை",category:"grocery",unit:"kg",normCost:0},
  {id:1171,name:"Dhall - Black Gram",nameTamil:"பருப்பு - கருப்பு உளுந்து",category:"grocery",unit:"kg",normCost:0},
  {id:1172,name:"Dhall - Green Gram",nameTamil:"பருப்பு - பாசிப்பயறு",category:"grocery",unit:"kg",normCost:0},
  {id:1173,name:"Dhall - Masur Dal",nameTamil:"பருப்பு - மசூர் பருப்பு",category:"grocery",unit:"kg",normCost:0},
  {id:1174,name:"Dhall - Mochai",nameTamil:"பருப்பு - மொச்சை",category:"grocery",unit:"kg",normCost:0},
  {id:1175,name:"Dhall - Moong Dal",nameTamil:"பருப்பு - பாசிப்பருப்பு",category:"grocery",unit:"kg",normCost:0},
  {id:1176,name:"Dhall - Mullaikatta Pasipayaru",nameTamil:"பருப்பு - முளைகட்டிய பாசிப்பயறு",category:"grocery",unit:"kg",normCost:0},
  {id:1177,name:"Dhall - Peas Dal",nameTamil:"பருப்பு - பட்டாணி பருப்பு",category:"grocery",unit:"kg",normCost:0},
  {id:1178,name:"Dhall - Rajma",nameTamil:"பருப்பு - ராஜ்மா",category:"grocery",unit:"kg",normCost:0},
  {id:1179,name:"Dhall - Small White Channa",nameTamil:"பருப்பு - சிறிய வெள்ளை கொண்டைக்கடலை",category:"grocery",unit:"kg",normCost:0},
  {id:1180,name:"Dhall - Thattapayaru Red",nameTamil:"பருப்பு - சிவப்பு தட்டைப்பயறு",category:"grocery",unit:"kg",normCost:0},
  {id:1181,name:"Dhall - Toor Dal",nameTamil:"பருப்பு - துவரம் பருப்பு",category:"grocery",unit:"kg",normCost:0},
  {id:1182,name:"Dhall - Urad",nameTamil:"பருப்பு - உளுந்து",category:"grocery",unit:"kg",normCost:0},
  {id:1183,name:"Dhall - Urad (for Idly)",nameTamil:"பருப்பு - இட்லிக்கான உளுந்து",category:"grocery",unit:"kg",normCost:0},
  {id:1184,name:"Dhall - Urad for Seasoning",nameTamil:"பருப்பு - தாளிப்புக்கான உளுந்து",category:"grocery",unit:"kg",normCost:0},
  {id:1185,name:"Dhall - White Channa",nameTamil:"பருப்பு - வெள்ளை கொண்டைக்கடலை",category:"grocery",unit:"kg",normCost:0},
  {id:1186,name:"Dhall- Pasi Payaru",nameTamil:"பருப்பு - பாசிப்பயறு",category:"grocery",unit:"kg",normCost:0},
  {id:1187,name:"Dhall- White Soya",nameTamil:"பருப்பு - வெள்ளை சோயா",category:"grocery",unit:"kg",normCost:0},
  {id:1188,name:"Dhall- white Thattai Payaru",nameTamil:"பருப்பு - வெள்ளை தட்டைப்பயறு",category:"grocery",unit:"kg",normCost:0},
  {id:1189,name:"Dhall-Pottu kadalai",nameTamil:"பருப்பு - பொட்டுக்கடலை",category:"grocery",unit:"kg",normCost:0},
  {id:1190,name:"Dhania",nameTamil:"தனியா",category:"grocery",unit:"kg",normCost:0},
  {id:1191,name:"Diamond Kalkandu",nameTamil:"டைமண்ட் கற்கண்டு",category:"grocery",unit:"kg",normCost:0},
  {id:1192,name:"Dough Weight",nameTamil:"பிசைந்த மாவு எடை",category:"grocery",unit:"kg",normCost:0},
  {id:1193,name:"Dry Butter Beans",nameTamil:"உலர் பட்டர் பீன்ஸ்",category:"grocery",unit:"g",normCost:0},
  {id:1194,name:"Dry Double Beans",nameTamil:"உலர் டபுள் பீன்ஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1195,name:"Dry Pacchai Pattani",nameTamil:"உலர் பச்சைப் பட்டாணி",category:"grocery",unit:"kg",normCost:0},
  {id:1196,name:"Dry Peas",nameTamil:"உலர் பட்டாணி",category:"grocery",unit:"kg",normCost:0},
  {id:1197,name:"Dry Soya Beans",nameTamil:"உலர் சோயா பீன்ஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1198,name:"ENO Salt",nameTamil:"ஈனோ உப்பு",category:"grocery",unit:"g",normCost:0},
  {id:1199,name:"Ellu Podi",nameTamil:"எள் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1200,name:"Extra Chilly Powder",nameTamil:"கூடுதல் மிளகாய் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1201,name:"Fig",nameTamil:"அத்திப்பழம்",category:"grocery",unit:"g",normCost:0},
  {id:1202,name:"Flakes - Potato water",nameTamil:"உருளைக்கிழங்கு ஃப்ளேக்ஸ் தண்ணீர்",category:"grocery",unit:"L",normCost:0},
  {id:1203,name:"Fresh Cream",nameTamil:"புதிய கிரீம்",category:"grocery",unit:"L",normCost:0},
  {id:1204,name:"Fried Gram",nameTamil:"பொட்டுக்கடலை",category:"grocery",unit:"kg",normCost:0},
  {id:1205,name:"Fried Pakoda",nameTamil:"பொரித்த பகோடா",category:"grocery",unit:"kg",normCost:0},
  {id:1206,name:"G China Grass",nameTamil:"G சைனா கிராஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1207,name:"G Jaljira",nameTamil:"G ஜல் ஜீரா",category:"grocery",unit:"kg",normCost:0},
  {id:1208,name:"G Malas Mango",nameTamil:"G மலாஸ் மாம்பழம்",category:"grocery",unit:"kg",normCost:0},
  {id:1209,name:"G Malas Strawberry",nameTamil:"G மலாஸ் ஸ்ட்ராபெர்ரி",category:"grocery",unit:"kg",normCost:0},
  {id:1210,name:"G Richies Whip Cream Gold",nameTamil:"G ரிச்சீஸ் விப் கிரீம் கோல்ட்",category:"grocery",unit:"L",normCost:0},
  {id:1211,name:"G Sauce - Garlic Sauce",nameTamil:"G சாஸ் - பூண்டு சாஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1212,name:"G Sauce - Momos sauce",nameTamil:"G சாஸ் - மோமோஸ் சாஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1213,name:"G Starter - Batata Puri",nameTamil:"G ஸ்டார்டர் - பட்டாட்டா பூரி",category:"grocery",unit:"kg",normCost:0},
  {id:1214,name:"G Starter - Nachos Salsa",nameTamil:"G ஸ்டார்டர் - நாசோஸ் சால்சா",category:"grocery",unit:"kg",normCost:0},
  {id:1215,name:"G Starter - Nachos dip",nameTamil:"G ஸ்டார்டர் - நாசோஸ் டிப்",category:"grocery",unit:"kg",normCost:0},
  {id:1216,name:"GN CCN powder",nameTamil:"GN CCN பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1217,name:"GN Garlic Powder",nameTamil:"GN பூண்டு பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1218,name:"GN Gowra water",nameTamil:"GN கௌரா தண்ணீர்",category:"grocery",unit:"L",normCost:0},
  {id:1219,name:"GN Nutmeg",nameTamil:"GN ஜாதிக்காய்",category:"grocery",unit:"kg",normCost:0},
  {id:1220,name:"GN Pau Baji Spice",nameTamil:"GN பாவ் பாஜி மசாலா",category:"grocery",unit:"kg",normCost:0},
  {id:1221,name:"GN Phool Makana",nameTamil:"GN பூல் மக்கானா",category:"grocery",unit:"kg",normCost:0},
  {id:1222,name:"GN Sha Jira",nameTamil:"GN ஷா சீரகம்",category:"grocery",unit:"kg",normCost:0},
  {id:1223,name:"GN Tomato Juice",nameTamil:"GN தக்காளி ஜூஸ்",category:"grocery",unit:"L",normCost:0},
  {id:1224,name:"Garlic Paste",nameTamil:"பூண்டு பேஸ்ட்",category:"grocery",unit:"kg",normCost:0},
  {id:1225,name:"Garlic Powder",nameTamil:"பூண்டு பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1226,name:"Ghee",nameTamil:"நெய்",category:"grocery",unit:"g",normCost:0},
  {id:1227,name:"Gloves",nameTamil:"கையுறை",category:"grocery",unit:"nos",normCost:0},
  {id:1228,name:"Gobind Bhog Rice",nameTamil:"கோபிந்த் போக் அரிசி",category:"grocery",unit:"kg",normCost:0},
  {id:1229,name:"Gravy - Brown",nameTamil:"கிரேவி - பழுப்பு",category:"grocery",unit:"kg",normCost:0},
  {id:1230,name:"Green Chutney",nameTamil:"பச்சை சட்னி",category:"grocery",unit:"kg",normCost:0},
  {id:1231,name:"Ground Nut",nameTamil:"வேர்க்கடலை",category:"grocery",unit:"kg",normCost:0},
  {id:1232,name:"Gulaub Jamun",nameTamil:"குலாப் ஜாமுன்",category:"grocery",unit:"kg",normCost:0},
  {id:1233,name:"Honey",nameTamil:"தேன்",category:"grocery",unit:"kg",normCost:0},
  {id:1234,name:"Horse Gram",nameTamil:"கொள்ளு",category:"grocery",unit:"kg",normCost:0},
  {id:1235,name:"Ice Water",nameTamil:"ஐஸ் தண்ணீர்",category:"grocery",unit:"L",normCost:0},
  {id:1236,name:"Italian Herbs",nameTamil:"இத்தாலிய மூலிகைகள்",category:"grocery",unit:"kg",normCost:0},
  {id:1237,name:"Iyengar Podi",nameTamil:"ஐயங்கார் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1238,name:"Jam",nameTamil:"ஜாம்",category:"grocery",unit:"kg",normCost:0},
  {id:1239,name:"Jeera",nameTamil:"சீரகம்",category:"grocery",unit:"kg",normCost:0},
  {id:1240,name:"KTR Paneer",nameTamil:"KTR பனீர்",category:"grocery",unit:"kg",normCost:0},
  {id:1241,name:"Kaaju Kathli",nameTamil:"காஜு கட்லி",category:"grocery",unit:"kg",normCost:0},
  {id:1242,name:"Kadai Avakaai Mango Pickle",nameTamil:"கடை ஆவக்காய் மாங்காய் ஊறுகாய்",category:"grocery",unit:"kg",normCost:0},
  {id:1243,name:"Kadai Kodaranga Pickle",nameTamil:"கடை கொடாரங்காய் ஊறுகாய்",category:"grocery",unit:"kg",normCost:0},
  {id:1244,name:"Kadai Kongura Pickle",nameTamil:"கடை கொங்குரா ஊறுகாய்",category:"grocery",unit:"kg",normCost:0},
  {id:1245,name:"Kadai Lemon Pickle",nameTamil:"கடை எலுமிச்சை ஊறுகாய்",category:"grocery",unit:"kg",normCost:0},
  {id:1246,name:"Kadai Mango Thokku",nameTamil:"கடை மாங்காய் தொக்கு",category:"grocery",unit:"kg",normCost:0},
  {id:1247,name:"Kadai Mixed Veg. Pickle",nameTamil:"கடை கலவை காய்கறி ஊறுகாய்",category:"grocery",unit:"kg",normCost:0},
  {id:1248,name:"Kadai Pulichakeerai Thokku",nameTamil:"கடை புளிச்ச கீரை தொக்கு",category:"grocery",unit:"g",normCost:0},
  {id:1249,name:"Kadai Vadumango Pickle",nameTamil:"கடை வடுமாங்காய் ஊறுகாய்",category:"grocery",unit:"kg",normCost:0},
  {id:1250,name:"Kadalaimaavu Thaneer",nameTamil:"கடலை மாவு தண்ணீர்",category:"grocery",unit:"g",normCost:0},
  {id:1251,name:"Kadugu",nameTamil:"கடுகு",category:"grocery",unit:"kg",normCost:0},
  {id:1252,name:"Kalkandu",nameTamil:"கற்கண்டு",category:"grocery",unit:"kg",normCost:0},
  {id:1253,name:"Kalonji",nameTamil:"கருஞ்சீரகம்",category:"grocery",unit:"g",normCost:0},
  {id:1254,name:"Kambu",nameTamil:"கம்பு",category:"grocery",unit:"kg",normCost:0},
  {id:1255,name:"Karaboondhi",nameTamil:"காரா பூந்தி",category:"grocery",unit:"kg",normCost:0},
  {id:1256,name:"Karaitha Mavu Weight",nameTamil:"கரைத்த மாவு எடை",category:"grocery",unit:"kg",normCost:0},
  {id:1257,name:"Karamani",nameTamil:"காராமணி",category:"grocery",unit:"kg",normCost:0},
  {id:1258,name:"Karnataka Rasa Powder",nameTamil:"கர்நாடக ரசப் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1259,name:"Karuppatti",nameTamil:"கருப்பட்டி",category:"grocery",unit:"kg",normCost:0},
  {id:1260,name:"Kasuri Methi",nameTamil:"கசூரி மேத்தி",category:"grocery",unit:"kg",normCost:0},
  {id:1261,name:"Keppai Maa",nameTamil:"கேப்பை மாவு",category:"grocery",unit:"kg",normCost:0},
  {id:1262,name:"Khus Khus",nameTamil:"கசகசா",category:"grocery",unit:"kg",normCost:0},
  {id:1263,name:"Kismis",nameTamil:"கிஸ்மிஸ்",category:"grocery",unit:"g",normCost:0},
  {id:1264,name:"Kothitha Jeera Yaedai",nameTamil:"கொதித்த சீரக எடை",category:"grocery",unit:"kg",normCost:0},
  {id:1265,name:"Kova( Sweetless)",nameTamil:"கோவா (இனிப்பு இல்லாதது)",category:"grocery",unit:"kg",normCost:0},
  {id:1266,name:"Kulkand",nameTamil:"குல்கந்த்",category:"grocery",unit:"kg",normCost:0},
  {id:1267,name:"Kuru Milagu",nameTamil:"குறு மிளகு",category:"grocery",unit:"kg",normCost:0},
  {id:1268,name:"Levista Coffee Powder",nameTamil:"லெவிஸ்டா காபி பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1269,name:"Lijjat Pappad",nameTamil:"லிஜ்ஜத் பாப்பட்",category:"grocery",unit:"kg",normCost:0},
  {id:1270,name:"Lion Date Syrup",nameTamil:"லயன் பேரீச்சம் பழ சிரப்",category:"grocery",unit:"L",normCost:0},
  {id:1271,name:"Maagi Cubes",nameTamil:"மேகி க்யூப்ஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1272,name:"Maavu Javvurisi",nameTamil:"மாவு ஜவ்வரிசி",category:"grocery",unit:"g",normCost:0},
  {id:1273,name:"Maavu Pisaiya Tata Salt",nameTamil:"மாவு பிசைக்க டாடா உப்பு",category:"grocery",unit:"g",normCost:0},
  {id:1274,name:"Mace Javitri,",nameTamil:"ஜாதிப்பத்திரி",category:"grocery",unit:"kg",normCost:0},
  {id:1275,name:"Makka Cholam",nameTamil:"மக்காச்சோளம்",category:"grocery",unit:"kg",normCost:0},
  {id:1276,name:"Manathakkali",nameTamil:"மணத்தக்காளி",category:"grocery",unit:"kg",normCost:0},
  {id:1277,name:"Manchurian Gravy Yaedai",nameTamil:"மஞ்சூரியன் கிரேவி எடை",category:"grocery",unit:"kg",normCost:0},
  {id:1278,name:"Manda Jaggery",nameTamil:"மண்டா வெல்லம்",category:"grocery",unit:"kg",normCost:0},
  {id:1279,name:"Masala Paal Podi",nameTamil:"மசாலா பால் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1280,name:"Mavu-Arisi mavu weight",nameTamil:"மாவு - அரிசி மாவு எடை",category:"grocery",unit:"kg",normCost:0},
  {id:1281,name:"Mavu-Attiya Mavu Weight",nameTamil:"மாவு - அடித்த மாவு எடை",category:"grocery",unit:"kg",normCost:0},
  {id:1282,name:"Mavu-Rice with soaked water",nameTamil:"மாவு - ஊறிய தண்ணீருடன் அரிசி",category:"grocery",unit:"L",normCost:0},
  {id:1283,name:"Mavu-Ulunthu Mavu Wt",nameTamil:"மாவு - உளுந்து மாவு எடை",category:"grocery",unit:"kg",normCost:0},
  {id:1284,name:"Mayonnaise",nameTamil:"மயோனெய்ஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1285,name:"Mealmaker",nameTamil:"மீல் மேக்கர்",category:"grocery",unit:"kg",normCost:0},
  {id:1286,name:"Milk - Milk (Paneer) AC",nameTamil:"பால் - பனீருக்கான பால் AC",category:"grocery",unit:"L",normCost:0},
  {id:1287,name:"Millet - Kuthuravali",nameTamil:"சிறுதானியம் - குதிரைவாலி",category:"grocery",unit:"g",normCost:0},
  {id:1288,name:"Millet - Samai",nameTamil:"சிறுதானியம் - சாமை",category:"grocery",unit:"kg",normCost:0},
  {id:1289,name:"Millet - Thinai",nameTamil:"சிறுதானியம் - திணை",category:"grocery",unit:"kg",normCost:0},
  {id:1290,name:"Millet - Varagu",nameTamil:"சிறுதானியம் - வரகு",category:"grocery",unit:"kg",normCost:0},
  {id:1291,name:"Millets-Keppai",nameTamil:"சிறுதானியம் - கேப்பை",category:"grocery",unit:"kg",normCost:0},
  {id:1292,name:"Mineral Water 300 ml",nameTamil:"மினரல் வாட்டர் 300 மி.லி.",category:"grocery",unit:"L",normCost:0},
  {id:1293,name:"Moo Kadalai",nameTamil:"மூக்கடலை",category:"grocery",unit:"kg",normCost:0},
  {id:1294,name:"Morde Dark Choclate",nameTamil:"மோர்டே டார்க் சாக்லேட்",category:"grocery",unit:"kg",normCost:0},
  {id:1295,name:"Morde Milk Compound",nameTamil:"மோர்டே மில்க் காம்பவுண்ட்",category:"grocery",unit:"L",normCost:0},
  {id:1296,name:"MusTARD",nameTamil:"கடுகு",category:"grocery",unit:"kg",normCost:0},
  {id:1297,name:"Mustard Paste",nameTamil:"கடுகு பேஸ்ட்",category:"grocery",unit:"kg",normCost:0},
  {id:1298,name:"Nannari",nameTamil:"நன்னாரி",category:"grocery",unit:"kg",normCost:0},
  {id:1299,name:"Narasus Decoction",nameTamil:"நரசுஸ் டிகாக்ஷன்",category:"grocery",unit:"L",normCost:0},
  {id:1300,name:"Nattu Sakkarai",nameTamil:"நாட்டு சர்க்கரை",category:"grocery",unit:"kg",normCost:0},
  {id:1301,name:"Neelavembu",nameTamil:"நிலவேம்பு",category:"grocery",unit:"kg",normCost:0},
  {id:1302,name:"Nestea",nameTamil:"நெஸ்டியா",category:"grocery",unit:"kg",normCost:0},
  {id:1303,name:"Nilavembu",nameTamil:"நிலவேம்பு",category:"grocery",unit:"kg",normCost:0},
  {id:1304,name:"Noodles - Chinese Noodles",nameTamil:"நூடுல்ஸ் - சீன நூடுல்ஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1305,name:"Noodles - Maggie Noodles",nameTamil:"நூடுல்ஸ் - மேகி நூடுல்ஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1306,name:"Nutmeg",nameTamil:"ஜாதிக்காய்",category:"grocery",unit:"kg",normCost:0},
  {id:1307,name:"Oats",nameTamil:"ஓட்ஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1308,name:"Oil - Coconut Oil",nameTamil:"எண்ணெய் - தேங்காய் எண்ணெய்",category:"grocery",unit:"L",normCost:0},
  {id:1309,name:"Oil - GN sesame oil",nameTamil:"எண்ணெய் - GN நல்லெண்ணெய்",category:"grocery",unit:"L",normCost:0},
  {id:1310,name:"Oil - Mustard oil",nameTamil:"எண்ணெய் - கடுகு எண்ணெய்",category:"grocery",unit:"L",normCost:0},
  {id:1311,name:"Oil - Oil",nameTamil:"எண்ணெய் - எண்ணெய்",category:"grocery",unit:"L",normCost:0},
  {id:1312,name:"Oil - Oil (Veg)",nameTamil:"எண்ணெய் - காய்கறிக்கான எண்ணெய்",category:"grocery",unit:"L",normCost:0},
  {id:1313,name:"Oil - Oil for Flour Kneading",nameTamil:"எண்ணெய் - மாவு பிசைக்க எண்ணெய்",category:"grocery",unit:"L",normCost:0},
  {id:1314,name:"Oil - Oil for Frying",nameTamil:"எண்ணெய் - பொரிக்க எண்ணெய்",category:"grocery",unit:"L",normCost:0},
  {id:1315,name:"Oil - Oil for Seasoning",nameTamil:"எண்ணெய் - தாளிக்க எண்ணெய்",category:"grocery",unit:"L",normCost:0},
  {id:1316,name:"Oil - Olive oil",nameTamil:"எண்ணெய் - ஆலிவ் எண்ணெய்",category:"grocery",unit:"L",normCost:0},
  {id:1317,name:"Oil - Sesame Oil",nameTamil:"எண்ணெய் - நல்லெண்ணெய்",category:"grocery",unit:"L",normCost:0},
  {id:1318,name:"Oil - Sesame Oil KAL",nameTamil:"எண்ணெய் - நல்லெண்ணெய் KAL",category:"grocery",unit:"L",normCost:0},
  {id:1319,name:"Old Batter",nameTamil:"பழைய மாவு",category:"grocery",unit:"kg",normCost:0},
  {id:1320,name:"Old Idly",nameTamil:"பழைய இட்லி",category:"grocery",unit:"kg",normCost:0},
  {id:1321,name:"Omam",nameTamil:"ஓமம்",category:"grocery",unit:"g",normCost:0},
  {id:1322,name:"Omapodi",nameTamil:"ஓமப்பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1323,name:"Onion Seeds",nameTamil:"வெங்காய விதை",category:"grocery",unit:"g",normCost:0},
  {id:1324,name:"Onion Vathal",nameTamil:"வெங்காய வத்தல்",category:"grocery",unit:"kg",normCost:0},
  {id:1325,name:"Organo",nameTamil:"ஓரிகானோ",category:"grocery",unit:"kg",normCost:0},
  {id:1326,name:"Own Decoction",nameTamil:"சொந்த டிகாக்ஷன்",category:"grocery",unit:"L",normCost:0},
  {id:1327,name:"Packing Box",nameTamil:"பேக்கிங் பெட்டி",category:"grocery",unit:"nos",normCost:0},
  {id:1328,name:"Pakku Mara Plate",nameTamil:"பாக்கு மர தட்டு",category:"grocery",unit:"nos",normCost:0},
  {id:1329,name:"Palada",nameTamil:"பாலடா",category:"grocery",unit:"kg",normCost:0},
  {id:1330,name:"Palm Kalkandu",nameTamil:"பனை கற்கண்டு",category:"grocery",unit:"kg",normCost:0},
  {id:1331,name:"Pani Puri",nameTamil:"பானி பூரி",category:"grocery",unit:"kg",normCost:0},
  {id:1332,name:"Pani Puri Masala Powder",nameTamil:"பானி பூரி மசாலா பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1333,name:"Papadam",nameTamil:"பாப்படம்",category:"grocery",unit:"kg",normCost:0},
  {id:1334,name:"Paper Plate",nameTamil:"காகிதத் தட்டு",category:"grocery",unit:"nos",normCost:0},
  {id:1335,name:"Paprika Powder",nameTamil:"பாப்ரிகா பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1336,name:"Parsley",nameTamil:"பார்ஸ்லி",category:"grocery",unit:"kg",normCost:0},
  {id:1337,name:"Pasta - Farfalle",nameTamil:"பாஸ்தா - ஃபார்ஃபாலே",category:"grocery",unit:"kg",normCost:0},
  {id:1338,name:"Pasta - Fusili",nameTamil:"பாஸ்தா - ஃபுசில்லி",category:"grocery",unit:"kg",normCost:0},
  {id:1339,name:"Pasta - Macaroni",nameTamil:"பாஸ்தா - மக்கரோனி",category:"grocery",unit:"kg",normCost:0},
  {id:1340,name:"Pav Bun",nameTamil:"பாவ் பன்",category:"grocery",unit:"kg",normCost:0},
  {id:1341,name:"Payasam Kaichiya Alavu",nameTamil:"பாயாசம் காய்ச்சிய அளவு",category:"grocery",unit:"kg",normCost:0},
  {id:1342,name:"Pepper",nameTamil:"மிளகு",category:"grocery",unit:"g",normCost:0},
  {id:1343,name:"Pickle - Garlic Pickle",nameTamil:"ஊறுகாய் - பூண்டு ஊறுகாய்",category:"grocery",unit:"kg",normCost:0},
  {id:1344,name:"Pickle - Ginger Tamarind",nameTamil:"ஊறுகாய் - இஞ்சி புளி",category:"grocery",unit:"kg",normCost:0},
  {id:1345,name:"Pickle - Ginger Thokku",nameTamil:"ஊறுகாய் - இஞ்சி தொக்கு",category:"grocery",unit:"kg",normCost:0},
  {id:1346,name:"Pickle - Onion Thokku",nameTamil:"ஊறுகாய் - வெங்காய தொக்கு",category:"grocery",unit:"kg",normCost:0},
  {id:1347,name:"Pidi Kozhukattai Maavu",nameTamil:"பிடி கொழுக்கட்டை மாவு",category:"grocery",unit:"g",normCost:0},
  {id:1348,name:"Pisainta Mavu Weight",nameTamil:"பிசைந்த மாவு எடை",category:"grocery",unit:"kg",normCost:0},
  {id:1349,name:"Pizza Seasoning Powder",nameTamil:"பீட்சா சீசனிங் பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1350,name:"Podi - Bajji Mix",nameTamil:"பொடி - பஜ்ஜி மிக்ஸ்",category:"grocery",unit:"g",normCost:0},
  {id:1351,name:"Poondu Podi Pickle",nameTamil:"பூண்டு பொடி ஊறுகாய்",category:"grocery",unit:"g",normCost:0},
  {id:1352,name:"Poondu Podiyaga Vettiyadhu",nameTamil:"பொடியாக நறுக்கிய பூண்டு",category:"grocery",unit:"g",normCost:0},
  {id:1353,name:"Poppy Seeds",nameTamil:"கசகசா",category:"grocery",unit:"g",normCost:0},
  {id:1354,name:"Pori",nameTamil:"பொரி",category:"grocery",unit:"kg",normCost:0},
  {id:1355,name:"Potato Chips",nameTamil:"உருளைக்கிழங்கு சிப்ஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1356,name:"Pumpkin Seed",nameTamil:"பூசணி விதை",category:"grocery",unit:"g",normCost:0},
  {id:1357,name:"Q.Coffee",nameTamil:"க்யூ. காபி",category:"grocery",unit:"kg",normCost:0},
  {id:1358,name:"Ragi",nameTamil:"கேழ்வரகு",category:"grocery",unit:"kg",normCost:0},
  {id:1359,name:"Ragi Maavu",nameTamil:"கேழ்வரகு மாவு",category:"grocery",unit:"g",normCost:0},
  {id:1360,name:"Rasagulla",nameTamil:"ரசகுல்லா",category:"grocery",unit:"kg",normCost:0},
  {id:1361,name:"Rasam",nameTamil:"ரசம்",category:"grocery",unit:"kg",normCost:0},
  {id:1362,name:"Rava Mix",nameTamil:"ரவை மிக்ஸ்",category:"grocery",unit:"g",normCost:0},
  {id:1363,name:"Raw Ground Nut",nameTamil:"பச்சை வேர்க்கடலை",category:"grocery",unit:"kg",normCost:0},
  {id:1364,name:"Raw Jack Fruit",nameTamil:"பச்சை பலாக்காய்",category:"grocery",unit:"kg",normCost:0},
  {id:1365,name:"Raw Papaya",nameTamil:"பச்சை பப்பாளி",category:"grocery",unit:"kg",normCost:0},
  {id:1366,name:"Readymade Poori",nameTamil:"ரெடிமேட் பூரி",category:"grocery",unit:"kg",normCost:0},
  {id:1367,name:"Red Aval",nameTamil:"சிவப்பு அவல்",category:"grocery",unit:"kg",normCost:0},
  {id:1368,name:"Redchilli Garlic Vinegar",nameTamil:"சிவப்பு மிளகாய் பூண்டு வினிகர்",category:"grocery",unit:"L",normCost:0},
  {id:1369,name:"Rice - Basmathi",nameTamil:"அரிசி - பாஸ்மதி",category:"grocery",unit:"kg",normCost:0},
  {id:1370,name:"Rice - IR 20",nameTamil:"அரிசி - IR 20",category:"grocery",unit:"kg",normCost:0},
  {id:1371,name:"Rice - IdlyRice (IR 20)",nameTamil:"அரிசி - இட்லி அரிசி (IR 20)",category:"grocery",unit:"kg",normCost:0},
  {id:1372,name:"Rice - Kavuni",nameTamil:"அரிசி - கவுனி",category:"grocery",unit:"kg",normCost:0},
  {id:1373,name:"Rice - Kuruvai",nameTamil:"அரிசி - குறுவை",category:"grocery",unit:"kg",normCost:0},
  {id:1374,name:"Rice - Paniyara",nameTamil:"அரிசி - பணியார அரிசி",category:"grocery",unit:"kg",normCost:0},
  {id:1375,name:"Rice - Ponni Paccharisi",nameTamil:"அரிசி - பொன்னி பச்சரிசி",category:"grocery",unit:"kg",normCost:0},
  {id:1376,name:"Rice - Ponni Puzhangal",nameTamil:"அரிசி - பொன்னி புழுங்கல்",category:"grocery",unit:"kg",normCost:0},
  {id:1377,name:"Rice - Seerga Samba",nameTamil:"அரிசி - சீரக சம்பா",category:"grocery",unit:"kg",normCost:0},
  {id:1378,name:"Rice-Tiffin Rice",nameTamil:"அரிசி - டிபன் அரிசி",category:"grocery",unit:"kg",normCost:0},
  {id:1379,name:"Roasted Bambino Semiya",nameTamil:"வறுத்த பாம்பினோ சேமியா",category:"grocery",unit:"kg",normCost:0},
  {id:1380,name:"Roasted Chick Peas",nameTamil:"வறுத்த கொண்டைக்கடலை",category:"grocery",unit:"kg",normCost:0},
  {id:1381,name:"Roasted Peanut",nameTamil:"வறுத்த வேர்க்கடலை",category:"grocery",unit:"g",normCost:0},
  {id:1382,name:"Rose Essence",nameTamil:"ரோஸ் எசன்ஸ்",category:"grocery",unit:"L",normCost:0},
  {id:1383,name:"S S Plate",nameTamil:"எஸ்.எஸ். தட்டு",category:"grocery",unit:"nos",normCost:0},
  {id:1384,name:"Saffron",nameTamil:"குங்குமப்பூ",category:"grocery",unit:"kg",normCost:0},
  {id:1385,name:"Samba Wheat",nameTamil:"சம்பா கோதுமை",category:"grocery",unit:"kg",normCost:0},
  {id:1386,name:"Sathu Maavu",nameTamil:"சத்துமாவு",category:"grocery",unit:"g",normCost:0},
  {id:1387,name:"Sauce - Chilli Sauce",nameTamil:"சாஸ் - மிளகாய் சாஸ்",category:"grocery",unit:"g",normCost:0},
  {id:1388,name:"Sauce - Mayonaise Sauce",nameTamil:"சாஸ் - மயோனெய்ஸ் சாஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1389,name:"Sauce - Pasta Sauce",nameTamil:"சாஸ் - பாஸ்தா சாஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1390,name:"Sauce - Red Chilli Sauce",nameTamil:"சாஸ் - சிவப்பு மிளகாய் சாஸ்",category:"grocery",unit:"g",normCost:0},
  {id:1391,name:"Sauce - Schezwan Sauce",nameTamil:"சாஸ் - செஷ்வான் சாஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1392,name:"Sauce - Soya Sauce",nameTamil:"சாஸ் - சோயா சாஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1393,name:"Sauce - Sweet Chilli Sauce",nameTamil:"சாஸ் - இனிப்பு மிளகாய் சாஸ்",category:"grocery",unit:"g",normCost:0},
  {id:1394,name:"Sauce - Tomato Sauce",nameTamil:"சாஸ் - தக்காளி சாஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1395,name:"Sauce - White Sauce",nameTamil:"சாஸ் - வெள்ளை சாஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1396,name:"Schezwan Chutney (Rita Arora)",nameTamil:"செஷ்வான் சட்னி (ரிதா அரோரா)",category:"grocery",unit:"kg",normCost:0},
  {id:1397,name:"Silver Spoon",nameTamil:"வெள்ளி ஸ்பூன்",category:"grocery",unit:"nos",normCost:0},
  {id:1398,name:"Sombu",nameTamil:"சோம்பு",category:"grocery",unit:"kg",normCost:0},
  {id:1399,name:"Sombu Powder",nameTamil:"சோம்பு பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1400,name:"Soya Beans",nameTamil:"சோயா பீன்ஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1401,name:"Soya Chunks",nameTamil:"சோயா சங்",category:"grocery",unit:"kg",normCost:0},
  {id:1402,name:"Star anise",nameTamil:"அன்னாசிப் பூ",category:"grocery",unit:"g",normCost:0},
  {id:1403,name:"Starter - Cheesy Corn Nuggets",nameTamil:"ஸ்டார்டர் - சீசி கார்ன் நகெட்ஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1404,name:"Stock Water",nameTamil:"ஸ்டாக் தண்ணீர்",category:"grocery",unit:"L",normCost:0},
  {id:1405,name:"Sugar",nameTamil:"சர்க்கரை",category:"grocery",unit:"g",normCost:0},
  {id:1406,name:"Sugar Syrup",nameTamil:"சர்க்கரை பாகு",category:"grocery",unit:"L",normCost:0},
  {id:1407,name:"Sukku",nameTamil:"சுக்கு",category:"grocery",unit:"kg",normCost:0},
  {id:1408,name:"Sukku Powder",nameTamil:"சுக்கு பொடி",category:"grocery",unit:"g",normCost:0},
  {id:1409,name:"Sweet Green Chutney",nameTamil:"இனிப்பு பச்சை சட்னி",category:"grocery",unit:"kg",normCost:0},
  {id:1410,name:"Sweet Sombu",nameTamil:"இனிப்பு சோம்பு",category:"grocery",unit:"kg",normCost:0},
  {id:1411,name:"T.Rice - Karunkuruvai",nameTamil:"பாரம்பரிய அரிசி - கருங்குறுவை",category:"grocery",unit:"kg",normCost:0},
  {id:1412,name:"T.Rice - Kattuyanam",nameTamil:"பாரம்பரிய அரிசி - காட்டுயானம்",category:"grocery",unit:"kg",normCost:0},
  {id:1413,name:"T.Rice - Mappillai Samba",nameTamil:"பாரம்பரிய அரிசி - மாப்பிள்ளை சம்பா",category:"grocery",unit:"kg",normCost:0},
  {id:1414,name:"T.Rice - Moongil",nameTamil:"பாரம்பரிய அரிசி - மூங்கில் அரிசி",category:"grocery",unit:"kg",normCost:0},
  {id:1415,name:"T.Rice - Navara",nameTamil:"பாரம்பரிய அரிசி - நவரா",category:"grocery",unit:"kg",normCost:0},
  {id:1416,name:"T.Rice - Poongar",nameTamil:"பாரம்பரிய அரிசி - பூங்கார்",category:"grocery",unit:"kg",normCost:0},
  {id:1417,name:"TR-Thooyamalli Rice",nameTamil:"பாரம்பரிய அரிசி - தூயமல்லி அரிசி",category:"grocery",unit:"kg",normCost:0},
  {id:1418,name:"Tamarind",nameTamil:"புளி",category:"grocery",unit:"kg",normCost:0},
  {id:1419,name:"Tamarind Juice",nameTamil:"புளிச்சாறு",category:"grocery",unit:"L",normCost:0},
  {id:1420,name:"Tamarind( Veg)",nameTamil:"காய்கறிக்கான புளி",category:"grocery",unit:"kg",normCost:0},
  {id:1421,name:"Tamarind(Water)",nameTamil:"புளித்தண்ணீர்",category:"grocery",unit:"L",normCost:0},
  {id:1422,name:"Tang",nameTamil:"டாங்",category:"grocery",unit:"kg",normCost:0},
  {id:1423,name:"Tang Mango",nameTamil:"டாங் மாம்பழம்",category:"grocery",unit:"kg",normCost:0},
  {id:1424,name:"Tata Salt",nameTamil:"டாடா உப்பு",category:"grocery",unit:"g",normCost:0},
  {id:1425,name:"Tata Salt ( For Veg)",nameTamil:"டாடா உப்பு (காய்கறிக்காக)",category:"grocery",unit:"g",normCost:0},
  {id:1426,name:"Tata Salt (Masala)",nameTamil:"டாடா உப்பு (மசாலா)",category:"grocery",unit:"g",normCost:0},
  {id:1427,name:"Tender Coconut",nameTamil:"இளநீர்",category:"grocery",unit:"kg",normCost:0},
  {id:1428,name:"Thalippu Vadagam",nameTamil:"தாளிப்பு வடகம்",category:"grocery",unit:"kg",normCost:0},
  {id:1429,name:"Tomato Ketchup",nameTamil:"தக்காளி கெட்சப்",category:"grocery",unit:"kg",normCost:0},
  {id:1430,name:"Tomato Paste",nameTamil:"தக்காளி பேஸ்ட்",category:"grocery",unit:"kg",normCost:0},
  {id:1431,name:"Tomato Thokku",nameTamil:"தக்காளி தொக்கு",category:"grocery",unit:"kg",normCost:0},
  {id:1432,name:"True Semia",nameTamil:"ட்ரூ சேமியா",category:"grocery",unit:"kg",normCost:0},
  {id:1433,name:"Tutti Frutti",nameTamil:"டூட்டி ஃப்ரூட்டி",category:"grocery",unit:"kg",normCost:0},
  {id:1434,name:"Varagu",nameTamil:"வரகு",category:"grocery",unit:"kg",normCost:0},
  {id:1435,name:"Varuthu Araitha Wheat Ma",nameTamil:"வறுத்து அரைத்த கோதுமை மாவு",category:"grocery",unit:"kg",normCost:0},
  {id:1436,name:"Vathal - Mor Milagaai",nameTamil:"வத்தல் - மோர் மிளகாய்",category:"grocery",unit:"kg",normCost:0},
  {id:1437,name:"Vathal Appala Poo",nameTamil:"வத்தல் அப்பளப் பூ",category:"grocery",unit:"kg",normCost:0},
  {id:1438,name:"Vathal Arisi",nameTamil:"வத்தல் அரிசி",category:"grocery",unit:"kg",normCost:0},
  {id:1439,name:"Vathal Avarai",nameTamil:"வத்தல் அவரை",category:"grocery",unit:"kg",normCost:0},
  {id:1440,name:"Vathal Bat",nameTamil:"வத்தல் பேட்",category:"grocery",unit:"kg",normCost:0},
  {id:1441,name:"Vathal Brinjal",nameTamil:"வத்தல் கத்தரிக்காய்",category:"grocery",unit:"kg",normCost:0},
  {id:1442,name:"Vathal Chinese Border",nameTamil:"வத்தல் சீனீஸ் போர்டர்",category:"grocery",unit:"kg",normCost:0},
  {id:1443,name:"Vathal Corn Flakes",nameTamil:"வத்தல் கார்ன் ஃப்ளேக்ஸ்",category:"grocery",unit:"kg",normCost:0},
  {id:1444,name:"Vathal Diamond",nameTamil:"வத்தல் டைமண்ட்",category:"grocery",unit:"kg",normCost:0},
  {id:1445,name:"Vathal Garlic",nameTamil:"வத்தல் பூண்டு",category:"grocery",unit:"kg",normCost:0},
  {id:1446,name:"Vathal Heart",nameTamil:"வத்தல் இதயம்",category:"grocery",unit:"kg",normCost:0},
  {id:1447,name:"Vathal Javurisi Coin",nameTamil:"வத்தல் ஜவ்வரிசி நாணயம்",category:"grocery",unit:"kg",normCost:0},
  {id:1448,name:"Vathal Koozh",nameTamil:"வத்தல் கூழ்",category:"grocery",unit:"kg",normCost:0},
  {id:1449,name:"Vathal Kothavarangaai",nameTamil:"வத்தல் கொத்தவரங்காய்",category:"grocery",unit:"kg",normCost:0},
  {id:1450,name:"Vathal Maa Vathal",nameTamil:"வத்தல் மாவத்தல்",category:"grocery",unit:"kg",normCost:0},
  {id:1451,name:"Vathal Milagaai",nameTamil:"வத்தல் மிளகாய்",category:"grocery",unit:"kg",normCost:0},
  {id:1452,name:"Vathal Murukku",nameTamil:"வத்தல் முறுக்கு",category:"grocery",unit:"kg",normCost:0},
  {id:1453,name:"Vathal Neetu",nameTamil:"வத்தல் நீட்டு",category:"grocery",unit:"kg",normCost:0},
  {id:1454,name:"Vathal Nila",nameTamil:"வத்தல் நிலா",category:"grocery",unit:"kg",normCost:0},
  {id:1455,name:"Vathal Omapodi Vadam",nameTamil:"வத்தல் ஓமப்பொடி வடம்",category:"grocery",unit:"g",normCost:0},
  {id:1456,name:"Vathal Paani Poodi",nameTamil:"வத்தல் பானி பூரி",category:"grocery",unit:"kg",normCost:0},
  {id:1457,name:"Vathal Poondu",nameTamil:"வத்தல் பூண்டு",category:"grocery",unit:"kg",normCost:0},
  {id:1458,name:"Vathal Serial Round",nameTamil:"வத்தல் சீரியல் ரவுண்ட்",category:"grocery",unit:"kg",normCost:0},
  {id:1459,name:"Vathal Sundakaai",nameTamil:"வத்தல் சுண்டைக்காய்",category:"grocery",unit:"kg",normCost:0},
  {id:1460,name:"Vathal Triangle",nameTamil:"வத்தல் முக்கோணம்",category:"grocery",unit:"kg",normCost:0},
  {id:1461,name:"Vathal Ulundhu",nameTamil:"வத்தல் உளுந்து",category:"grocery",unit:"kg",normCost:0},
  {id:1462,name:"Vathal Vellai Surya",nameTamil:"வத்தல் வெள்ளை சூர்யா",category:"grocery",unit:"kg",normCost:0},
  {id:1463,name:"Vathal Vengayam",nameTamil:"வத்தல் வெங்காயம்",category:"grocery",unit:"kg",normCost:0},
  {id:1464,name:"Vathal White Ring",nameTamil:"வத்தல் வெள்ளை ரிங்",category:"grocery",unit:"kg",normCost:0},
  {id:1465,name:"Vathiya Paal",nameTamil:"வத்திய பால்",category:"grocery",unit:"kg",normCost:0},
  {id:1466,name:"Vegetable After Fry",nameTamil:"வறுத்த பிறகு காய்கறி",category:"grocery",unit:"kg",normCost:0},
  {id:1467,name:"Vellai Kavuni Arsi",nameTamil:"வெள்ளை கவுனி அரிசி",category:"grocery",unit:"kg",normCost:0},
  {id:1468,name:"Vellari Vedhai",nameTamil:"வெள்ளரி விதை",category:"grocery",unit:"kg",normCost:0},
  {id:1469,name:"Vendhayam",nameTamil:"வெந்தயம்",category:"grocery",unit:"kg",normCost:0},
  {id:1470,name:"Vennilla Essence",nameTamil:"வெனிலா எசன்ஸ்",category:"grocery",unit:"L",normCost:0},
  {id:1471,name:"Vinegar",nameTamil:"வினிகர்",category:"grocery",unit:"L",normCost:0},
  {id:1472,name:"Virali Manjal",nameTamil:"விரலி மஞ்சள்",category:"grocery",unit:"kg",normCost:0},
  {id:1473,name:"Water",nameTamil:"தண்ணீர்",category:"grocery",unit:"L",normCost:0},
  {id:1474,name:"Water Melon Seeds",nameTamil:"தர்பூசணி விதை",category:"grocery",unit:"L",normCost:0},
  {id:1475,name:"Water for Basen",nameTamil:"கடலை மாவுக்கான தண்ணீர்",category:"grocery",unit:"L",normCost:0},
  {id:1476,name:"Water(Kozhambu)",nameTamil:"தண்ணீர் (குழம்பு)",category:"grocery",unit:"L",normCost:0},
  {id:1477,name:"Wheat",nameTamil:"கோதுமை",category:"grocery",unit:"kg",normCost:0},
  {id:1478,name:"Wheat Dalia",nameTamil:"கோதுமை தலியா",category:"grocery",unit:"kg",normCost:0},
  {id:1479,name:"Wheat Pasta",nameTamil:"கோதுமை பாஸ்தா",category:"grocery",unit:"kg",normCost:0},
  {id:1480,name:"Wheat Rava",nameTamil:"கோதுமை ரவை",category:"grocery",unit:"g",normCost:0},
  {id:1481,name:"White Cholam",nameTamil:"வெள்ளை சோளம்",category:"grocery",unit:"kg",normCost:0},
  {id:1482,name:"White Ellu",nameTamil:"வெள்ளை எள்",category:"grocery",unit:"g",normCost:0},
  {id:1483,name:"White Peas",nameTamil:"வெள்ளை பட்டாணி",category:"grocery",unit:"kg",normCost:0},
  {id:1484,name:"White Pepper",nameTamil:"வெள்ளை மிளகு",category:"grocery",unit:"g",normCost:0},
  {id:1485,name:"Yeadu",nameTamil:"ஏடு",category:"grocery",unit:"kg",normCost:0},
  {id:1486,name:"Yeast",nameTamil:"ஈஸ்ட்",category:"grocery",unit:"kg",normCost:0},
  {id:1487,name:"Pilakottai",nameTamil:"பிலாக்கொட்டை",category:"vegetable",unit:"kg",normCost:0},
  {id:1488,name:"5 Portion Plate",nameTamil:"5 பகுதி தட்டு",category:"vegetable",unit:"nos",normCost:0},
  {id:1489,name:"AC Agathi Keerai",nameTamil:"AC அகத்திக்கீரை",category:"vegetable",unit:"g",normCost:0},
  {id:1490,name:"AC AraiKeerai",nameTamil:"AC அரைக்கீரை",category:"vegetable",unit:"g",normCost:0},
  {id:1491,name:"AC Ash Gourd",nameTamil:"AC பூசணிக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1492,name:"AC Baby Corn",nameTamil:"AC பேபி கார்ன்",category:"vegetable",unit:"kg",normCost:0},
  {id:1493,name:"AC Baby Potato",nameTamil:"AC குட்டி உருளைக்கிழங்கு",category:"vegetable",unit:"kg",normCost:0},
  {id:1494,name:"AC Banana (Naan)",nameTamil:"AC வாழைப்பழம் (நான்)",category:"vegetable",unit:"kg",normCost:0},
  {id:1495,name:"AC Banana Flower",nameTamil:"AC வாழைப்பூ",category:"vegetable",unit:"kg",normCost:0},
  {id:1496,name:"AC Banana Stem",nameTamil:"AC வாழைத்தண்டு",category:"vegetable",unit:"kg",normCost:0},
  {id:1497,name:"AC Beans",nameTamil:"AC பீன்ஸ்",category:"vegetable",unit:"kg",normCost:0},
  {id:1498,name:"AC Beetroot",nameTamil:"AC பீட்ரூட்",category:"vegetable",unit:"kg",normCost:0},
  {id:1499,name:"AC Bottle Gourd",nameTamil:"AC சுரைக்காய்",category:"vegetable",unit:"nos",normCost:0},
  {id:1500,name:"AC Brinjal",nameTamil:"AC கத்தரிக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1501,name:"AC Broad Beans",nameTamil:"AC அவரைக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1502,name:"AC Broccoli",nameTamil:"AC பிரோக்கோலி",category:"vegetable",unit:"kg",normCost:0},
  {id:1503,name:"AC Butter Beans",nameTamil:"AC பட்டர் பீன்ஸ்",category:"vegetable",unit:"g",normCost:0},
  {id:1504,name:"AC Cabbage",nameTamil:"AC முட்டைக்கோஸ்",category:"vegetable",unit:"kg",normCost:0},
  {id:1505,name:"AC Capsicum",nameTamil:"AC குடைமிளகாய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1506,name:"AC Carrot",nameTamil:"AC கேரட்",category:"vegetable",unit:"kg",normCost:0},
  {id:1507,name:"AC Cauli Flower",nameTamil:"AC காலிஃபிளவர்",category:"vegetable",unit:"kg",normCost:0},
  {id:1508,name:"AC Chow Chow",nameTamil:"AC சௌ சௌ",category:"vegetable",unit:"kg",normCost:0},
  {id:1509,name:"AC Cluster Beans",nameTamil:"AC கொத்தவரங்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1510,name:"AC Colacasia",nameTamil:"AC சேப்பங்கிழங்கு",category:"vegetable",unit:"kg",normCost:0},
  {id:1511,name:"AC Cucumber",nameTamil:"AC வெள்ளரிக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1512,name:"AC Drumstick Leaf",nameTamil:"AC முருங்கைக்கீரை",category:"vegetable",unit:"g",normCost:0},
  {id:1513,name:"AC Fresh Double Beans",nameTamil:"AC பச்சை டபுள் பீன்ஸ்",category:"vegetable",unit:"kg",normCost:0},
  {id:1514,name:"AC Fresh Peas",nameTamil:"AC பச்சைப் பட்டாணி",category:"vegetable",unit:"kg",normCost:0},
  {id:1515,name:"AC Green Grapes",nameTamil:"AC பச்சை திராட்சை",category:"vegetable",unit:"kg",normCost:0},
  {id:1516,name:"AC Guava",nameTamil:"AC கொய்யாப்பழம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1517,name:"AC Jackfruit",nameTamil:"AC பலாப்பழம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1518,name:"AC Karunaikizhangu",nameTamil:"AC கருணைக்கிழங்கு",category:"vegetable",unit:"kg",normCost:0},
  {id:1519,name:"AC Keerai",nameTamil:"AC கீரை",category:"vegetable",unit:"g",normCost:0},
  {id:1520,name:"AC Keerini",nameTamil:"AC கீரிணி",category:"vegetable",unit:"kg",normCost:0},
  {id:1521,name:"AC Kovakkai",nameTamil:"AC கோவைக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1522,name:"AC Lady's Finger",nameTamil:"AC வெண்டைக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1523,name:"AC Mango Fruit",nameTamil:"AC மாம்பழம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1524,name:"AC Mango Ginger",nameTamil:"AC மாங்காய் இஞ்சி",category:"vegetable",unit:"kg",normCost:0},
  {id:1525,name:"AC Methi Keerai",nameTamil:"AC வெந்தயக்கீரை",category:"vegetable",unit:"g",normCost:0},
  {id:1526,name:"AC Mint",nameTamil:"AC புதினா",category:"vegetable",unit:"kg",normCost:0},
  {id:1527,name:"AC Onion",nameTamil:"AC வெங்காயம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1528,name:"AC Palak",nameTamil:"AC பசலைக்கீரை",category:"vegetable",unit:"kg",normCost:0},
  {id:1529,name:"AC Papaya Fruit",nameTamil:"AC பப்பாளிப் பழம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1530,name:"AC Papaya Veg",nameTamil:"AC பச்சை பப்பாளி",category:"vegetable",unit:"kg",normCost:0},
  {id:1531,name:"AC Paruppu Keerai",nameTamil:"AC பருப்புக்கீரை",category:"vegetable",unit:"g",normCost:0},
  {id:1532,name:"AC Pineapple",nameTamil:"AC அன்னாசிப்பழம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1533,name:"AC Pomogranate",nameTamil:"AC மாதுளம்பழம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1534,name:"AC Potato",nameTamil:"AC உருளைக்கிழங்கு",category:"vegetable",unit:"kg",normCost:0},
  {id:1535,name:"AC Radish",nameTamil:"AC முள்ளங்கி",category:"vegetable",unit:"kg",normCost:0},
  {id:1536,name:"AC Raw Banana",nameTamil:"AC வாழைக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1537,name:"AC Raw Jack Fruit",nameTamil:"AC பச்சை பலாக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1538,name:"AC Raw Mango",nameTamil:"AC பச்சை மாங்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1539,name:"AC Red Pumpkin",nameTamil:"AC சிவப்பு பூசணிக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1540,name:"AC Ridge Gourd",nameTamil:"AC பீர்க்கங்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1541,name:"AC Sappotta",nameTamil:"AC சப்போட்டா",category:"vegetable",unit:"kg",normCost:0},
  {id:1542,name:"AC Snake Gourd",nameTamil:"AC புடலங்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1543,name:"AC Soya Beans",nameTamil:"AC சோயா பீன்ஸ்",category:"vegetable",unit:"kg",normCost:0},
  {id:1544,name:"AC Sweet Corn",nameTamil:"AC இனிப்பு சோளம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1545,name:"AC Tapaico",nameTamil:"AC மரவள்ளிக்கிழங்கு",category:"vegetable",unit:"kg",normCost:0},
  {id:1546,name:"AC Thattapayathangai",nameTamil:"AC தட்டைப்பயத்தங்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1547,name:"AC Violet Cabbage",nameTamil:"AC ஊதா முட்டைக்கோஸ்",category:"vegetable",unit:"kg",normCost:0},
  {id:1548,name:"AC Watermelon",nameTamil:"AC தர்பூசணி",category:"vegetable",unit:"L",normCost:0},
  {id:1549,name:"AC Yam",nameTamil:"AC சேனைக்கிழங்கு",category:"vegetable",unit:"kg",normCost:0},
  {id:1550,name:"AC vazhaipoo",nameTamil:"AC வாழைப்பூ",category:"vegetable",unit:"kg",normCost:0},
  {id:1551,name:"Aavin Curd",nameTamil:"ஆவின் தயிர்",category:"vegetable",unit:"L",normCost:0},
  {id:1552,name:"Agathi Keerai",nameTamil:"அகத்திக்கீரை",category:"vegetable",unit:"g",normCost:0},
  {id:1553,name:"Amla",nameTamil:"நெல்லிக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1554,name:"Apple",nameTamil:"ஆப்பிள்",category:"vegetable",unit:"kg",normCost:0},
  {id:1555,name:"Arai Keerai",nameTamil:"அரைக்கீரை",category:"vegetable",unit:"g",normCost:0},
  {id:1556,name:"Ash Gourd",nameTamil:"பூசணிக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1557,name:"Baby Brinjal",nameTamil:"குட்டி கத்தரிக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1558,name:"Baby Corn",nameTamil:"பேபி கார்ன்",category:"vegetable",unit:"kg",normCost:0},
  {id:1559,name:"Baby Corn Box",nameTamil:"பேபி கார்ன் பெட்டி",category:"vegetable",unit:"nos",normCost:0},
  {id:1560,name:"Baby Potato",nameTamil:"குட்டி உருளைக்கிழங்கு",category:"vegetable",unit:"kg",normCost:0},
  {id:1561,name:"Bajji Chilli",nameTamil:"பஜ்ஜி மிளகாய்",category:"vegetable",unit:"g",normCost:0},
  {id:1562,name:"Bajji Milagaai AC",nameTamil:"பஜ்ஜி மிளகாய் AC",category:"vegetable",unit:"kg",normCost:0},
  {id:1563,name:"Bajji Milagai",nameTamil:"பஜ்ஜி மிளகாய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1564,name:"Banana Flower",nameTamil:"வாழைப்பூ",category:"vegetable",unit:"kg",normCost:0},
  {id:1565,name:"Banana Fruit",nameTamil:"வாழைப்பழம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1566,name:"Banana Stem",nameTamil:"வாழைத்தண்டு",category:"vegetable",unit:"kg",normCost:0},
  {id:1567,name:"Beans",nameTamil:"பீன்ஸ்",category:"vegetable",unit:"kg",normCost:0},
  {id:1568,name:"Beet Root",nameTamil:"பீட்ரூட்",category:"vegetable",unit:"kg",normCost:0},
  {id:1569,name:"Bisleri 300 ml",nameTamil:"பிஸ்லேரி 300 மி.லி.",category:"vegetable",unit:"kg",normCost:0},
  {id:1570,name:"Bitter Gourd",nameTamil:"பாகற்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1571,name:"Bottle Gourd",nameTamil:"சுரைக்காய்",category:"vegetable",unit:"nos",normCost:0},
  {id:1572,name:"Brinjal Ujala",nameTamil:"உஜாலா கத்தரிக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1573,name:"Broad Beans",nameTamil:"அவரைக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1574,name:"Broccoli",nameTamil:"பிரோக்கோலி",category:"vegetable",unit:"kg",normCost:0},
  {id:1575,name:"Butter Beans",nameTamil:"பட்டர் பீன்ஸ்",category:"vegetable",unit:"g",normCost:0},
  {id:1576,name:"Buttermilk",nameTamil:"மோர்",category:"vegetable",unit:"L",normCost:0},
  {id:1577,name:"Cabbage",nameTamil:"முட்டைக்கோஸ்",category:"vegetable",unit:"kg",normCost:0},
  {id:1578,name:"Capsicum",nameTamil:"குடைமிளகாய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1579,name:"Carrot",nameTamil:"கேரட்",category:"vegetable",unit:"kg",normCost:0},
  {id:1580,name:"Cauliflower",nameTamil:"காலிஃபிளவர்",category:"vegetable",unit:"kg",normCost:0},
  {id:1581,name:"Chips Potato",nameTamil:"சிப்ஸ் உருளைக்கிழங்கு",category:"vegetable",unit:"kg",normCost:0},
  {id:1582,name:"Chow Chow",nameTamil:"சௌ சௌ",category:"vegetable",unit:"kg",normCost:0},
  {id:1583,name:"Cluster Beans",nameTamil:"கொத்தவரங்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1584,name:"Coconut",nameTamil:"தேங்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1585,name:"Coconut Pal",nameTamil:"தேங்காய் பால்",category:"vegetable",unit:"kg",normCost:0},
  {id:1586,name:"Colacasia",nameTamil:"சேப்பங்கிழங்கு",category:"vegetable",unit:"kg",normCost:0},
  {id:1587,name:"Coriander Leaves",nameTamil:"கொத்தமல்லி இலை",category:"vegetable",unit:"g",normCost:0},
  {id:1588,name:"Corriender Leaf",nameTamil:"கொத்தமல்லி இலை",category:"vegetable",unit:"g",normCost:0},
  {id:1589,name:"Cucumber",nameTamil:"வெள்ளரிக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1590,name:"Curd",nameTamil:"தயிர்",category:"vegetable",unit:"L",normCost:0},
  {id:1591,name:"Curd - Old yogurt",nameTamil:"தயிர் - பழைய தயிர்",category:"vegetable",unit:"L",normCost:0},
  {id:1592,name:"Curry Leaf",nameTamil:"கருவேப்பிலை",category:"vegetable",unit:"g",normCost:0},
  {id:1593,name:"Dosa Batter",nameTamil:"தோசை மாவு",category:"vegetable",unit:"kg",normCost:0},
  {id:1594,name:"Drumstick",nameTamil:"முருங்கைக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1595,name:"Drumstick Leaf",nameTamil:"முருங்கைக்கீரை",category:"vegetable",unit:"g",normCost:0},
  {id:1596,name:"Elaneer Halwa",nameTamil:"இளநீர் அல்வா",category:"vegetable",unit:"kg",normCost:0},
  {id:1597,name:"FROZEN PEAS",nameTamil:"உறைந்த பட்டாணி",category:"vegetable",unit:"kg",normCost:0},
  {id:1598,name:"Flakes- Garlic",nameTamil:"பூண்டு ஃப்ளேக்ஸ்",category:"vegetable",unit:"kg",normCost:0},
  {id:1599,name:"Flakes- Onion",nameTamil:"வெங்காய ஃப்ளேக்ஸ்",category:"vegetable",unit:"kg",normCost:0},
  {id:1600,name:"Flakes-Potato",nameTamil:"உருளைக்கிழங்கு ஃப்ளேக்ஸ்",category:"vegetable",unit:"kg",normCost:0},
  {id:1601,name:"Fresh Double Beans",nameTamil:"பச்சை டபுள் பீன்ஸ்",category:"vegetable",unit:"kg",normCost:0},
  {id:1602,name:"Fresh Peas",nameTamil:"பச்சைப் பட்டாணி",category:"vegetable",unit:"kg",normCost:0},
  {id:1603,name:"Fruit - Mango",nameTamil:"பழம் - மாம்பழம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1604,name:"Garlic",nameTamil:"பூண்டு",category:"vegetable",unit:"kg",normCost:0},
  {id:1605,name:"Garlic AC",nameTamil:"பூண்டு AC",category:"vegetable",unit:"kg",normCost:0},
  {id:1606,name:"Ginger",nameTamil:"இஞ்சி",category:"vegetable",unit:"kg",normCost:0},
  {id:1607,name:"Green Chilli",nameTamil:"பச்சை மிளகாய்",category:"vegetable",unit:"g",normCost:0},
  {id:1608,name:"Green Mochai",nameTamil:"பச்சை மொச்சை",category:"vegetable",unit:"kg",normCost:0},
  {id:1609,name:"Hatsun Curd",nameTamil:"ஹட்சன் தயிர்",category:"vegetable",unit:"L",normCost:0},
  {id:1610,name:"Hatsun Curd Box",nameTamil:"ஹட்சன் தயிர் பெட்டி",category:"vegetable",unit:"L",normCost:0},
  {id:1611,name:"Kala Kos",nameTamil:"கலா கோஸ்",category:"vegetable",unit:"kg",normCost:0},
  {id:1612,name:"Kalakos",nameTamil:"கலா கோஸ்",category:"vegetable",unit:"kg",normCost:0},
  {id:1613,name:"Karunai Kizhangu",nameTamil:"கருணைக்கிழங்கு",category:"vegetable",unit:"kg",normCost:0},
  {id:1614,name:"Karupatti Kaaju Kathli",nameTamil:"கருப்பட்டி காஜு கட்லி",category:"vegetable",unit:"kg",normCost:0},
  {id:1615,name:"Keerai",nameTamil:"கீரை",category:"vegetable",unit:"g",normCost:0},
  {id:1616,name:"Kosmalli Brinjal",nameTamil:"கோஸ்மல்லி கத்தரிக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1617,name:"Kovakkai",nameTamil:"கோவைக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1618,name:"Lady's Finger",nameTamil:"வெண்டைக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1619,name:"Leaf- Round Ilai",nameTamil:"இலை - வட்ட இலை",category:"vegetable",unit:"g",normCost:0},
  {id:1620,name:"Lemon",nameTamil:"எலுமிச்சை",category:"vegetable",unit:"kg",normCost:0},
  {id:1621,name:"Lemon Juice",nameTamil:"எலுமிச்சை சாறு",category:"vegetable",unit:"L",normCost:0},
  {id:1622,name:"Letcha Ketta Keerai",nameTamil:"லெட்ச கெட்ட கீரை",category:"vegetable",unit:"g",normCost:0},
  {id:1623,name:"Long Snake Gourd",nameTamil:"நீளமான புடலங்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1624,name:"Manathakkali Keerai",nameTamil:"மணத்தக்காளி கீரை",category:"vegetable",unit:"g",normCost:0},
  {id:1625,name:"Mango Ginger",nameTamil:"மாங்காய் இஞ்சி",category:"vegetable",unit:"kg",normCost:0},
  {id:1626,name:"Methi Leaf",nameTamil:"வெந்தய இலை",category:"vegetable",unit:"g",normCost:0},
  {id:1627,name:"Milk (Brown Pack)",nameTamil:"பால் (பிரவுன் பாக்கெட்)",category:"vegetable",unit:"L",normCost:0},
  {id:1628,name:"Milk - Milk",nameTamil:"பால் - பால்",category:"vegetable",unit:"L",normCost:0},
  {id:1629,name:"Milk - Milk (Orange pack)",nameTamil:"பால் - பால் (ஆரஞ்சு பாக்கெட்)",category:"vegetable",unit:"L",normCost:0},
  {id:1630,name:"Milk - Milk (Paneer)",nameTamil:"பால் - பனீருக்கான பால்",category:"vegetable",unit:"L",normCost:0},
  {id:1631,name:"Milk - Milk (Yogurt)",nameTamil:"பால் - தயிருக்கான பால்",category:"vegetable",unit:"L",normCost:0},
  {id:1632,name:"Milky Mist Panner",nameTamil:"மில்கி மிஸ்ட் பனீர்",category:"vegetable",unit:"L",normCost:0},
  {id:1633,name:"Milkymist Paneer",nameTamil:"மில்கி மிஸ்ட் பனீர்",category:"vegetable",unit:"L",normCost:0},
  {id:1634,name:"Mint leaf",nameTamil:"புதினா இலை",category:"vegetable",unit:"g",normCost:0},
  {id:1635,name:"Mudakathan Keerai",nameTamil:"முடக்கத்தான் கீரை",category:"vegetable",unit:"g",normCost:0},
  {id:1636,name:"Mudakathan Keerai AC",nameTamil:"முடக்கத்தான் கீரை AC",category:"vegetable",unit:"g",normCost:0},
  {id:1637,name:"Mushroom",nameTamil:"காளான்",category:"vegetable",unit:"kg",normCost:0},
  {id:1638,name:"Navin Tomato Cut",nameTamil:"நவீன் நறுக்கிய தக்காளி",category:"vegetable",unit:"kg",normCost:0},
  {id:1639,name:"Navin Tomato Juice",nameTamil:"நவீன் தக்காளி ஜூஸ்",category:"vegetable",unit:"L",normCost:0},
  {id:1640,name:"Neem Flower",nameTamil:"வேப்பம்பூ",category:"vegetable",unit:"kg",normCost:0},
  {id:1641,name:"Nellikaai",nameTamil:"நெல்லிக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1642,name:"Nendhram Fruit",nameTamil:"நேந்திரம் பழம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1643,name:"Noolkol",nameTamil:"நூல்கோல்",category:"vegetable",unit:"kg",normCost:0},
  {id:1644,name:"Onion",nameTamil:"வெங்காயம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1645,name:"Onion Petals",nameTamil:"வெங்காய இதழ்கள்",category:"vegetable",unit:"kg",normCost:0},
  {id:1646,name:"Palak",nameTamil:"பசலைக்கீரை",category:"vegetable",unit:"kg",normCost:0},
  {id:1647,name:"Paneer Grapes",nameTamil:"பனீர் திராட்சை",category:"vegetable",unit:"kg",normCost:0},
  {id:1648,name:"Paruppu Keerai",nameTamil:"பருப்புக்கீரை",category:"vegetable",unit:"g",normCost:0},
  {id:1649,name:"Pineapple",nameTamil:"அன்னாசிப்பழம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1650,name:"Plantain Leaf",nameTamil:"வாழை இலை",category:"vegetable",unit:"g",normCost:0},
  {id:1651,name:"Pomogranate",nameTamil:"மாதுளம்பழம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1652,name:"Ponnanganni Keerai",nameTamil:"பொன்னாங்கண்ணி கீரை",category:"vegetable",unit:"g",normCost:0},
  {id:1653,name:"Potato( Mettupalayam)",nameTamil:"உருளைக்கிழங்கு (மேட்டுப்பாளையம்)",category:"vegetable",unit:"kg",normCost:0},
  {id:1654,name:"Radish",nameTamil:"முள்ளங்கி",category:"vegetable",unit:"kg",normCost:0},
  {id:1655,name:"Rasamalai",nameTamil:"ரசமலாய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1656,name:"Rasmalai",nameTamil:"ரசமலாய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1657,name:"Raw Banana",nameTamil:"வாழைக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1658,name:"Raw Jack Fruid",nameTamil:"பச்சை பலாக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1659,name:"Raw Mango",nameTamil:"பச்சை மாங்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1660,name:"Red Capsuicum",nameTamil:"சிவப்பு குடைமிளகாய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1661,name:"Red Pumpkin",nameTamil:"சிவப்பு பூசணிக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1662,name:"Ridge Gourd",nameTamil:"பீர்க்கங்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1663,name:"Riped Green Chilly",nameTamil:"பழுத்த பச்சை மிளகாய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1664,name:"Sakkara varatti",nameTamil:"சக்கர வரட்டி",category:"vegetable",unit:"kg",normCost:0},
  {id:1665,name:"Sakkaraivalli",nameTamil:"சக்கரைவள்ளி",category:"vegetable",unit:"kg",normCost:0},
  {id:1666,name:"Sappattu Ilai",nameTamil:"சாப்பாட்டு இலை",category:"vegetable",unit:"g",normCost:0},
  {id:1667,name:"Small Onion",nameTamil:"சின்ன வெங்காயம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1668,name:"Snake Gourd",nameTamil:"புடலங்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1669,name:"Sour Buttermilk",nameTamil:"புளித்த மோர்",category:"vegetable",unit:"L",normCost:0},
  {id:1670,name:"Spring Onion Green",nameTamil:"ஸ்பிரிங் ஆனியன் பச்சை பகுதி",category:"vegetable",unit:"kg",normCost:0},
  {id:1671,name:"Spring Onion White",nameTamil:"ஸ்பிரிங் ஆனியன் வெள்ளை பகுதி",category:"vegetable",unit:"kg",normCost:0},
  {id:1672,name:"Subal Brinjal",nameTamil:"சுபல் கத்தரிக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1673,name:"Sugarcane Plate 8 inch",nameTamil:"கரும்பு தட்டு 8 அங்குலம்",category:"vegetable",unit:"g",normCost:0},
  {id:1674,name:"Sundai Kai",nameTamil:"சுண்டைக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1675,name:"Sweet",nameTamil:"இனிப்பு",category:"vegetable",unit:"kg",normCost:0},
  {id:1676,name:"Sweet Corn",nameTamil:"இனிப்பு சோளம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1677,name:"Sweet Potato",nameTamil:"சக்கரைவள்ளிக் கிழங்கு",category:"vegetable",unit:"kg",normCost:0},
  {id:1678,name:"Tapaico",nameTamil:"மரவள்ளிக்கிழங்கு",category:"vegetable",unit:"kg",normCost:0},
  {id:1679,name:"Tender Coconut",nameTamil:"இளநீர்",category:"vegetable",unit:"kg",normCost:0},
  {id:1680,name:"Tender Coconut Vazhu",nameTamil:"இளநீர் வழு",category:"vegetable",unit:"kg",normCost:0},
  {id:1681,name:"Thattai Avaraikkai",nameTamil:"தட்டை அவரைக்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1682,name:"Thattapayathangai",nameTamil:"தட்டைப்பயத்தங்காய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1683,name:"Thennanguruthu",nameTamil:"தென்னங்குருத்து",category:"vegetable",unit:"kg",normCost:0},
  {id:1684,name:"Thennankuruthu",nameTamil:"தென்னங்குருத்து",category:"vegetable",unit:"kg",normCost:0},
  {id:1685,name:"Tiffin Thattu Ilai",nameTamil:"டிபன் தட்டு இலை",category:"vegetable",unit:"g",normCost:0},
  {id:1686,name:"Tomato Juice",nameTamil:"தக்காளி ஜூஸ்",category:"vegetable",unit:"L",normCost:0},
  {id:1687,name:"Tomato(Cut)",nameTamil:"தக்காளி (நறுக்கியது)",category:"vegetable",unit:"kg",normCost:0},
  {id:1688,name:"Topioca",nameTamil:"மரவள்ளிக்கிழங்கு",category:"vegetable",unit:"kg",normCost:0},
  {id:1689,name:"Turnip",nameTamil:"நூல்கோல்",category:"vegetable",unit:"kg",normCost:0},
  {id:1690,name:"VEG AFTER CUT",nameTamil:"நறுக்கிய பிறகு காய்கறி",category:"vegetable",unit:"kg",normCost:0},
  {id:1691,name:"Vathakkiya Weight",nameTamil:"வதக்கிய எடை",category:"vegetable",unit:"kg",normCost:0},
  {id:1692,name:"Vazhai Pattai",nameTamil:"வாழைப்பட்டை",category:"vegetable",unit:"kg",normCost:0},
  {id:1693,name:"Vazhaipoo",nameTamil:"வாழைப்பூ",category:"vegetable",unit:"kg",normCost:0},
  {id:1694,name:"Violet Cabbage",nameTamil:"ஊதா முட்டைக்கோஸ்",category:"vegetable",unit:"kg",normCost:0},
  {id:1695,name:"WATER BOTTLE",nameTamil:"தண்ணீர் பாட்டில்",category:"vegetable",unit:"L",normCost:0},
  {id:1696,name:"Yaedu",nameTamil:"ஏடு",category:"vegetable",unit:"kg",normCost:0},
  {id:1697,name:"Yam",nameTamil:"சேனைக்கிழங்கு",category:"vegetable",unit:"kg",normCost:0},
  {id:1698,name:"Yelaki Banana",nameTamil:"ஏலக்கி வாழைப்பழம்",category:"vegetable",unit:"kg",normCost:0},
  {id:1699,name:"Yellow Capsicum",nameTamil:"மஞ்சள் குடைமிளகாய்",category:"vegetable",unit:"kg",normCost:0},
  {id:1700,name:"Zuccini Green",nameTamil:"பச்சை சுக்கினி",category:"vegetable",unit:"kg",normCost:0},
  {id:1701,name:"Zuccini Yellow",nameTamil:"மஞ்சள் சுக்கினி",category:"vegetable",unit:"kg",normCost:0},
  {id:1702,name:"brinjal ujala",nameTamil:"உஜாலா கத்தரிக்காய்",category:"vegetable",unit:"kg",normCost:0},
];

const REC0=[];

const LOC0=[
  {id:1,name:"Main Hall",nameTamil:"முக்கிய மண்டபம்"},
  {id:2,name:"Old Age Home",nameTamil:"முதியோர் இல்லம்"},
  {id:3,name:"School",nameTamil:"பள்ளி"},
];

export const INV0 = { purchases: [], issues: [] };
export { RTYPE_SEED, ING0, REC0, LOC0 };
